services:
  - type: web
    name: moneyparce
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn moneyparce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: moneyparce.settings
      - key: PYTHON_VERSION
        value: 3.12