# Generated by Django 5.2 on 2025-04-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("transactions", "0004_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.category",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="month",
            field=models.DateField(auto_now_add=True),
        ),
    ]
