# Generated by Django 5.2 on 2025-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_budget_category_alter_budget_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
