# Generated by Django 5.0 on 2025-04-23 01:23

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('transactions', 'Category')
    defaults = [
        ('Rent/Mortgage', 'expense'),
        ('Utilities', 'expense'),
        ('Groceries', 'expense'),
        ('Dining Out', 'expense'),
        ('Transportation', 'expense'),
        ('Health', 'expense'),
        ('Entertainment', 'expense'),
        ('Shopping', 'expense'),
        ('Education', 'expense'),
        ('Insurance', 'expense'),
        ('Travel', 'expense'),
        ('Personal Care', 'expense'),
        ('Gifts/Donations', 'expense'),
        ('Debt Payments', 'expense'),
        ('Salary', 'income'),
        ('Freelance', 'income'),
        ('Investment', 'income'),
        ('Gifts', 'income'),
        ('Other Income', 'income'),
    ]

    for name, type in defaults:
        Category.objects.get_or_create(name=name, type=type)

class Migration(migrations.Migration):
    dependencies = [('transactions', '0001_initial')]  # adjust if needed
    operations = [migrations.RunPython(create_default_categories)]

