# Generated by Django 5.2 on 2025-04-29 11:14

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=encrypted_model_fields.fields.EncryptedCharField(default="0.00"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("income", "Income")], max_length=7
            ),
        ),
    ]
